import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { profile, projects } from './profile';
import './styles.css';
import './contact.css';

function Arrow({ diagonal = false, ...props }) { return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" {...props}>{diagonal ? <path d="M6 18 18 6M6 6h12v12" /> : <path d="M4 12h15m-6-6 6 6-6 6" />}</svg>; }
function Star({ className = '' }) { return <svg className={className} viewBox="0 0 100 100" aria-hidden="true"><path d="M50 0 59 32 85 15 68 41 100 50 68 59 85 85 59 68 50 100 41 68 15 85 32 59 0 50 32 41 15 15 41 32Z" fill="currentColor" /></svg>; }
function WebsiteArt() { return <div className="website-art" aria-label="Bhajan Sarita decorative project illustration"><div className="browser-bar"><span /><span /><span /><small>bhajansarita.com</small><span className="browser-plus">+</span></div><div className="website-inner"><div className="site-wordmark">bhajan sarita<span>शांति · भक्ति · आनंद</span></div><div className="sun-orbit"><div className="sun" /><span className="lotus">❋</span></div><div className="site-caption">A little more peace.<br /><em>A little more connection.</em></div><span className="art-label">WEBSITE PROJECT</span></div></div>; }

function App() {
  const [menu, setMenu] = useState(false);
  const [filter, setFilter] = useState('All projects');
  const [selected, setSelected] = useState(null);
  const [copied, setCopied] = useState(false);
  const dialog = useRef(null);
  useEffect(() => {
    if (selected && !dialog.current.open) dialog.current.showModal();
    if (!selected && dialog.current.open) dialog.current.close();
    if (!selected) return;
    const previous = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => { document.body.style.overflow = previous; };
  }, [selected]);
  async function copyEmail() {
    try { await navigator.clipboard.writeText(profile.email); setCopied(true); setTimeout(() => setCopied(false), 2500); }
    catch { window.location.href = `mailto:${profile.email}`; }
  }
  const visibleProjects = projects.filter(p => filter === 'All projects' || (filter === 'Applications' ? p.id !== 'bhakti' : p.id === 'bhakti'));
  return <>
    <a href="#main" className="skip-link">Skip to content</a>
    <header className="header"><a href="#" className="brand" aria-label="Portfolio home"><span className="brand-mark">&lt;/&gt;</span><span>{profile.name || 'devfolio'}<b>.</b></span></a><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-controls="navigation">{menu ? 'Close −' : 'Menu +'}</button><nav id="navigation" className={menu ? 'nav open' : 'nav'} aria-label="Main navigation">{[['Work', 'work'], ['About', 'about'], ['Expertise', 'expertise']].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}<a className="nav-contact" href="#contact" onClick={() => setMenu(false)}>Let’s talk <Arrow diagonal /></a></nav></header>
    <main id="main">
      <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="status-dot" /> {profile.role.toUpperCase()}</div><h1>Thoughtful code.<br />Meaningful<br /><span className="highlight">digital experiences.<svg viewBox="0 0 600 20" preserveAspectRatio="none"><path d="M3 14Q260-3 596 9" /></svg></span></h1><p>I build websites and applications with React.js, Next.js, and Node.js.<br className="desktop-break" /> From intuitive interfaces to backend functionality and SEO.</p><div className="hero-actions"><a href="#work" className="button dark">Explore my work <Arrow diagonal /></a><a href="#about" className="text-link">A little about me <Arrow /></a></div><div className="hero-footnote"><span>DESIGN-MINDED.</span><span>DETAIL-DRIVEN.</span><span>USER-FOCUSED.</span></div></div><div className="hero-visual"><div className="visual-topline"><span>IDEAS → INTERFACES</span><span>01 / 03</span></div><div className="dot-field" /><div className="orbit orbit-one" /><div className="orbit orbit-two" /><Star className="hero-star" /><div className="floating-label label-top"><span className="tiny-code">&lt;/&gt;</span> Built with intention</div><div className="hero-phone"><img src="/images/networth.png" alt="NetWorthApp dashboard showing total assets and recent holdings" fetchPriority="high" /></div><div className="floating-label label-bottom"><span className="label-icon">↗</span><div>From concept to screen<small>Clean interfaces. Real purpose.</small></div></div><span className="visual-bottomline">A SELECTED GLIMPSE OF MY WORK</span></div></section>
      <div className="skills-strip"><div className="wrap strip-inner"><span>THE BUILDING BLOCKS</span>{['React.js', 'Next.js', 'Node.js', 'JavaScript', 'SEO'].map(t => <React.Fragment key={t}><span className="strip-star">✳</span><strong>{t}</strong></React.Fragment>)}</div></div>
      <section className="section wrap" id="work"><div className="section-kicker"><span>01 / SELECTED WORK</span><span>IDEAS MADE REAL</span></div><div className="section-heading"><div><h2>A few things<br />I’ve brought to life<span>.</span></h2></div><p>Useful products. Considered interfaces.<br />Here’s a look at what I’ve been building.</p></div><div className="filters" aria-label="Filter projects">{['All projects', 'Applications', 'Websites'].map(f => <button key={f} className={filter === f ? 'active' : ''} onClick={() => setFilter(f)} aria-pressed={filter === f}>{f}{f === 'All projects' && <span>03</span>}</button>)}</div><div className="project-grid">{visibleProjects.map(p => <article key={p.id} className={`project-card project-${p.id}`}><button className="project-image" onClick={() => setSelected(p)} aria-label={`View ${p.name} project`}><span className="project-number">{p.number} /</span>{p.image ? <img src={p.image} alt={`${p.name} application screenshot`} loading="lazy" /> : <WebsiteArt />}<span className="project-open"><Arrow diagonal /></span></button><div className="project-meta"><span>{p.category}</span><span>{p.id === 'bhakti' ? 'WEB' : 'APP'}</span></div><button className="project-title" onClick={() => setSelected(p)}>{p.name}<Arrow diagonal /></button><p>{p.description}</p><div className="tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div></article>)}</div></section>
      <section className="about-section" id="about"><div className="wrap about-layout"><div className="about-art"><span className="about-art-label">THE PERSON BEHIND THE PIXELS</span><div className="code-art"><span className="code-comment">// a little about my approach</span><p><span>const</span> developer = {'{'}</p><p className="indent">mindset: <em>"curious"</em>,</p><p className="indent">focus: <em>"the details"</em>,</p><p className="indent">purpose: <em>"build useful things"</em></p><p>{'}'};</p><div className="code-line" /></div><Star className="about-star" /><span className="art-bottom">A HUMAN APPROACH TO DIGITAL WORK.</span></div><div className="about-copy"><div className="section-kicker">02 / A LITTLE ABOUT ME</div><h2>A developer’s logic.<br />A designer’s eye<span>.</span></h2><p>I’m {profile.name ? `${profile.name}, a` : 'a'} full stack developer working with React.js, Next.js, and Node.js. I bring together frontend development, backend functionality, and SEO to turn ideas into useful digital experiences.</p><p>My projects include NetWorthApp for organizing assets, ConctScan for managing business cards, and Bhajan Sarita, where my work includes full stack development and SEO. I care about how a website looks, how its functionality fits together, and how people discover its content.</p><div className="about-principles"><span><b>01</b> Clarity comes first</span><span><b>02</b> Details make the difference</span><span><b>03</b> Always keep learning</span></div>{profile.resumeUrl && <a className="text-link" href={profile.resumeUrl} target="_blank" rel="noreferrer">View my resume <Arrow diagonal /></a>}</div></div></section>
      <section className="section wrap" id="expertise"><div className="section-kicker">03 / WHAT I BRING</div><div className="section-heading"><h2>Good ideas deserve<br />great execution<span>.</span></h2><p>From the first layout to the final interaction,<br />I think about the whole experience.</p></div><div className="expertise-grid">{[{ icon: '</>', title: 'React.js & Next.js', text: 'Component-based interfaces and web pages that bring content, navigation, and interactions together. My frontend work focuses on clear layouts and a consistent experience across screen sizes.', tags: 'REACT.JS / NEXT.JS / JAVASCRIPT' }, { icon: '{ }', title: 'Node.js & full stack', text: 'Backend functionality that supports the interface. I work across the frontend and server side to connect application features and build complete web experiences.', tags: 'NODE.JS / BACKEND / FULL STACK' }, { icon: '↗', title: 'SEO & discoverability', text: 'Search engine optimization alongside development, including my work on Bhajan Sarita. I consider how content is presented and discovered as part of the overall website experience.', tags: 'SEO / CONTENT / WEB EXPERIENCE' }].map((x, i) => <article className="expertise-card" key={x.title}><div className="expertise-top"><span className="expertise-icon">{x.icon}</span><span>0{i + 1}</span></div><h3>{x.title}</h3><p>{x.text}</p><span className="expertise-tags">{x.tags}</span></article>)}</div></section>
      {(profile.experience.length > 0 || profile.education.length > 0) && <section className="wrap resume-section">{profile.experience.map((e, i) => <article key={i}><span>{e.period}</span><h3>{e.role} · {e.company}</h3><p>{e.description}</p></article>)}{profile.education.map((e, i) => <article key={i}><span>{e.period}</span><h3>{e.degree}</h3><p>{e.institution}</p></article>)}</section>}
      <section className="contact-section wrap" id="contact"><div className="contact-panel"><div className="section-kicker"><span>HAVE SOMETHING IN MIND?</span><Star /></div><h2>Let’s build<br />something <em>meaningful.</em></h2><div className="contact-bottom"><p>Need a full stack website, a React interface, or SEO support?<br />Connect with me on LinkedIn to discuss your project.</p>{profile.email ? <div className="contact-actions"><a className="button dark" href={`mailto:${profile.email}`}>Say hello <Arrow diagonal /></a><button className="copy-email" onClick={copyEmail}>{copied ? 'Email copied!' : 'Copy email'}</button><span role="status" className="sr-only">{copied ? 'Email copied to clipboard' : ''}</span></div> : <a className="button dark" href={profile.linkedin} target="_blank" rel="noreferrer">Let’s talk on LinkedIn <Arrow diagonal /></a>}</div><div className="contact-links"><span>{profile.name} · {profile.role}</span><div>{profile.linkedin && <a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <Arrow diagonal /></a>}{profile.github && <a href={profile.github} target="_blank" rel="noreferrer">GitHub <Arrow diagonal /></a>}</div></div></div></section>
    </main><footer className="wrap footer"><a className="brand" href="#"><span className="brand-mark">&lt;/&gt;</span><span>{profile.name || 'devfolio'}<b>.</b></span></a><span className="footer-description">Full stack development · React.js · Next.js · Node.js · SEO<br />© {new Date().getFullYear()} {profile.name}. Built with care.</span><div>{profile.github && <a href={profile.github} target="_blank" rel="noreferrer">GitHub <Arrow diagonal /></a>}{profile.linkedin && <a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <Arrow diagonal /></a>}<a href="#">Back to top ↑</a></div></footer>
    <dialog ref={dialog} onCancel={() => setSelected(null)} onClick={e => { if (e.target === dialog.current) setSelected(null); }} aria-labelledby="project-dialog-title"><button className="dialog-close" onClick={() => setSelected(null)} aria-label="Close project details">×</button>{selected && <div className="dialog-content">{selected.image ? <img src={selected.image} alt={`${selected.name} full application preview`} /> : <WebsiteArt />}<div className="dialog-copy"><span className="section-kicker">{selected.category}</span><h2 id="project-dialog-title">{selected.name}</h2><h3>{selected.headline}</h3><p>{selected.details}</p><div className="tags">{selected.tags.map(t => <span key={t}>{t}</span>)}</div>{selected.url && <a href={selected.url} className="button dark" target="_blank" rel="noreferrer">Visit website <Arrow diagonal /></a>}</div></div>}</dialog>
  </>;
}
createRoot(document.getElementById('root')).render(<App />);
